apiVersion: v1
kind: Service
metadata:
  name: "my-app-loadbalancer"
  namespace: "default"
  labels:
    app: "my-app-loadbalancer"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: my-app
  sessionAffinity: None
  type: LoadBalancer
