apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "my-app"
  namespace: "default"
  labels:
    app: "my-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "my-app"
  template:
    metadata:
      labels:
        app: "my-app"
    spec:
      containers:
      - name: "my-node-app"
        image: "my-node-app:v0.1"
        imagePullPolicy: Never
        command:
        - npm
        - start
